[package]
name = "minitia_fun"
version = "0.1.0"
authors = []

[addresses]
minitia_fun = "0xC0A7DD6C8EA3CCB58831B2878FB7365AF7BE5B80"
std = "0x1"
initia_std = "0x1"

[dev-addresses]
minitia_fun = "0xC0A7DD6C8EA3CCB58831B2878FB7365AF7BE5B80"

[dependencies.InitiaStdlib]
git = "https://github.com/initia-labs/movevm.git"
subdir = "precompile/modules/initia_stdlib"
rev = "v1.0.0"

[dependencies.MoveStdlib]
git = "https://github.com/initia-labs/movevm.git"
subdir = "precompile/modules/move_stdlib"
rev = "v1.0.0"
