[package]
name = "minitia_fun"
version = "0.1.0"
authors = []

[addresses]
minitia_fun = "_"
std = "0x1"
initia_std = "0x1"

[dev-addresses]
minitia_fun = "0xCAFE"

[dependencies.MoveStdlib]
git = "https://github.com/initia-labs/movevm.git"
subdir = "precompile/modules/move_stdlib"
rev = "main"

[dependencies.InitiaStdlib]
git = "https://github.com/initia-labs/movevm.git"
subdir = "precompile/modules/initia_stdlib"
rev = "main"
